version: "3.3"
services:
  zookeeper-1:
    image: zookeeper:3.6.3
    restart: always
    container_name: zookeeper-1
    hostname: zookeeper-1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888;2181
    networks:
      tisya-net:
        ipv4_address: 172.16.1.50

networks:
  tisya-net:
    external: true

  
